type StatesAndCities = {
  city: string;
  state: string;
};

export const statesAndCities: StatesAndCities[] = [
  { city: 'Aba', state: 'Abia' },
  { city: 'Umuahia', state: 'Abia' },
  { city: 'Yola', state: 'Adamawa' },
  { city: 'Uyo', state: 'Akwa Ibom' },
  { city: 'Awka', state: 'Anambra' },
  { city: 'Bauchi', state: 'Bauchi' },
  { city: 'Yenagoa', state: 'Bayelsa' },
  { city: 'Makurdi', state: 'Benue' },
  { city: 'Maiduguri', state: 'Borno' },
  { city: 'Calabar', state: 'Cross River' },
  { city: 'Asaba', state: 'Delta' },
  { city: 'Abakaliki', state: 'Ebonyi' },
  { city: 'Benin', state: 'Edo' },
  { city: 'Ado-Ekiti', state: 'Ekiti' },
  { city: 'Enugu', state: 'Enugu' },
  { city: 'Gombe', state: 'Gombe' },
  { city: 'Owerri', state: 'Imo' },
  { city: 'Dutse', state: 'Jigawa' },
  { city: 'Zaria', state: 'Kaduna' },
  { city: 'Kano', state: 'Kano' },
  { city: 'Katsina', state: 'Katsina' },
  { city: 'Birnin Kebbi', state: 'Kebbi' },
  { city: 'Lokoja', state: 'Kogi' },
  { city: 'Ilorin', state: 'Kwara' },
  { city: 'Ikeja', state: 'Lagos' },
  { city: 'Mararaba', state: 'Nasarawa' },
  { city: 'Minna', state: 'Niger' },
  { city: 'Abeokuta', state: 'Ogun' },
  { city: 'Akure', state: 'Ondo' },
  { city: 'Osogbo', state: 'Osun' },
  { city: 'Ibadan', state: 'Oyo' },
  { city: 'Jos', state: 'Plateau' },
  { city: 'Port Harcourt', state: 'Rivers' },
  { city: 'Sokoto', state: 'Sokoto' },
  { city: 'Jalingo', state: 'Taraba' },
  { city: 'Nguru', state: 'Yobe' },
  { city: 'Gusau', state: 'Zamfara' },
  { city: 'Garki', state: 'Abuja' },
];
