type StatesAndCities = {
  city: string;
  state: string;
};

export const statesAndCities: StatesAndCities[] = [
  { city: 'Aba', state: 'Abia' },
  { city: 'Umuahia', state: 'Abia' },
  { city: 'Beijing', state: 'China' },
  { city: 'Uyo', state: 'Akwa Ibom' },
  { city: 'Awka', state: 'Anambra' },
  { city: 'Arizona', state: 'USA' },
  { city: 'Yenagoa', state: 'Bayelsa' },
  { city: 'Makurdi', state: 'Benue' },
  { city: 'Accra', state: 'Ghana' },
  { city: 'Calabar', state: 'Cross River' },
  { city: 'Asaba', state: 'Delta' },
  { city: 'London', state: 'UK' },
  { city: 'Benin', state: 'Edo' },
  { city: 'Ado-Ekiti', state: 'Ekiti' },
  { city: 'Johannesburg', state: 'South Africa' },
  { city: 'Gombe', state: 'Gombe' },
  { city: 'Owerri', state: 'Imo' },
  { city: 'Nairobi', state: 'Kenya' },
  { city: 'Katsina', state: 'Katsina' },
  { city: 'Kano', state: 'Kano' },
  { city: 'Seoul', state: 'South Korea' },
  { city: 'Birnin Kebbi', state: 'Kebbi' },
  { city: 'Lokoja', state: 'Kogi' },
  { city: 'Tokyo', state: 'Japan' },
  { city: 'Ilorin', state: 'Kwara' },
  { city: 'Ikeja', state: 'Lagos' },
  { city: 'Cairo', state: 'Egypt' },
  { city: 'Abeokuta', state: 'Ogun' },
  { city: 'Akure', state: 'Ondo' },
  { city: 'Berlin', state: 'Germany' },
  { city: 'Ibadan', state: 'Oyo' },
  { city: 'Stockholm', state: 'Sweden' },
  { city: 'Port Harcourt', state: 'Rivers' },
  { city: 'Sokoto', state: 'Sokoto' },
  { city: 'Riyadh', state: 'Saudi Arabia' },
  { city: 'Nguru', state: 'Yobe' },
  { city: 'Chennai', state: 'India' },
  { city: 'Garki', state: 'Abuja' },
];
